[libraries]
com-apollographql-adapters-apollo-adapters-core = { module = "com.apollographql.adapters:apollo-adapters-core", version.ref = "com-apollographql-adapters" }
com-apollographql-adapters-apollo-adapters-kotlinx-datetime = { module = "com.apollographql.adapters:apollo-adapters-kotlinx-datetime", version.ref = "com-apollographql-adapters" }
com-apollographql-apollo-apollo-runtime = "com.apollographql.apollo:apollo-runtime:4.3.3"
com-apollographql-ktor-apollo-engine-ktor = "com.apollographql.ktor:apollo-engine-ktor:0.1.1"
com-fasterxml-jackson-core-jackson-databind = "com.fasterxml.jackson.core:jackson-databind:2.20.1"
com-github-ajalt-clikt-clikt = "com.github.ajalt.clikt:clikt:5.0.3"
com-lemonappdev-konsist = "com.lemonappdev:konsist:0.17.3"
com-zegreatrob-jsmints-jsmints-bom = "com.zegreatrob.jsmints:jsmints-bom:6.8.10"
com-zegreatrob-testmints-testmints-bom = "com.zegreatrob.testmints:testmints-bom:12.5.12"
com-zegreatrob-tools-tools-bom = "com.zegreatrob.tools:tools-bom:1.8.19"
io-github-oshai-kotlin-logging = "io.github.oshai:kotlin-logging:7.0.13"
io-ktor-ktor-bom = "io.ktor:ktor-bom:3.3.2"
org-jetbrains-kotlin-wrappers-kotlin-wrappers-bom = "org.jetbrains.kotlin-wrappers:kotlin-wrappers-bom:2025.11.3"
org-jetbrains-kotlinx-kotlinx-coroutines-bom = "org.jetbrains.kotlinx:kotlinx-coroutines-bom:1.10.2"
org-jetbrains-kotlinx-kotlinx-datetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.7.1-0.6.x-compat"
org-jetbrains-kotlinx-kotlinx-serialization-bom = "org.jetbrains.kotlinx:kotlinx-serialization-bom:1.9.0"
org-junit-junit-bom = "org.junit:junit-bom:6.0.1"
org-kotlincrypto-hash-bom = "org.kotlincrypto.hash:bom:0.8.0"
org-kotools-types = { module = "org.kotools:types", version.ref = "org-kotools" }
org-kotools-types-kotlinx-serialization = { module = "org.kotools:types-kotlinx-serialization", version.ref = "org-kotools" }
org-slf4j-slf4j-simple = "org.slf4j:slf4j-simple:2.0.17"

[plugins]
com-apollographql-apollo = "com.apollographql.apollo:4.3.3"
com-avast-gradle-docker-compose = "com.avast.gradle.docker-compose:0.17.19"
com-github-ben-manes-versions = "com.github.ben-manes.versions:0.53.0"
com-github-sghill-distribution-sha = "com.github.sghill.distribution-sha:0.4.0"
com-zegreatrob-tools-certifier = "com.zegreatrob.tools.certifier:1.8.19"
com-zegreatrob-tools-digger = "com.zegreatrob.tools.digger:1.8.19"
io-github-turansky-kfc-application = "io.github.turansky.kfc.application:16.0.0"
io-github-turansky-seskar = "io.github.turansky.seskar:4.27.0"
nl-littlerobots-version-catalog-update = "nl.littlerobots.version-catalog-update:1.0.1"

[versions]
com-apollographql-adapters = "0.7.0"
org-kotools = "5.0.1"
